const fs = require("fs");
const path = require("path");

const packageJson = require("../package.json");

const versionContent = `// Auto-generated by scripts/generate-version.js
// Do not edit manually - version comes from package.json

export const VERSION = "${packageJson.version}";
`;

const versionPath = path.join(__dirname, "..", "src", "version.ts");
fs.writeFileSync(versionPath, versionContent);
console.log(`Generated src/version.ts with VERSION = "${packageJson.version}"`);
